# Generated by Django 4.2.9 on 2024-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi:')),
                ('slug', models.SlugField(unique=True)),
                ('measurement_unit', models.CharField(max_length=10, verbose_name="O'lchov Birlik")),
                ('body_price', models.IntegerField(default=0, verbose_name='Sof Foydasi')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_added_with_hour', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
