# Generated by Django 4.2.9 on 2024-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='income',
            field=models.IntegerField(default=0, verbose_name='Sof Foydasi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_price',
            field=models.IntegerField(default=0, verbose_name='Tan Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(max_length=10, verbose_name="O'lchov Birligi"),
        ),
    ]
