# Generated by Django 4.2.9 on 2024-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_product_income_alter_product_body_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Miqdori'),
        ),
    ]
