# Generated by Django 4.2.9 on 2024-05-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
