# Generated by Django 4.2.9 on 2024-05-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nomi:')),
                ('body_price', models.IntegerField(blank=True, default=0, verbose_name='Tan Narxi')),
                ('income', models.IntegerField(blank=True, default=0, verbose_name='Sof Foydasi')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='Miqdori')),
                ('measurement_unit', models.CharField(blank=True, max_length=10, verbose_name="O'lchov Birligi")),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_added_with_hour', models.DateTimeField(auto_now_add=True)),
                ('max_amount', models.IntegerField(blank=True, default=0, verbose_name='Limiti')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.storage', verbose_name='Ombori')),
            ],
        ),
    ]
