# Generated by Django 4.2.9 on 2024-05-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Mijozning Ismi')),
                ('amount', models.FloatField(default=0, verbose_name='summasi')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Sanansi')),
                ('payment_type', models.CharField(max_length=250, verbose_name="To'lov turi")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('extra_phone_number', models.CharField(max_length=20, verbose_name="Qo'shimcha raqam")),
            ],
        ),
    ]
