# Generated by Django 4.2.9 on 2024-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expances',
            name='currency',
            field=models.CharField(default="so'm", max_length=100, verbose_name='Valyuta'),
        ),
    ]
