# Generated by Django 4.2.9 on 2024-05-03 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expances', '0002_expances_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='expances',
            name='deadline',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expances',
            name='currency',
            field=models.CharField(default="so'm", max_length=100),
        ),
    ]
