# Generated by Django 4.2.9 on 2024-05-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expances', '0003_expances_deadline_alter_expances_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expances',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Mijozning Ismi'),
        ),
    ]
