# Generated by Django 4.2.9 on 2024-05-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_alter_product_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('product_amount', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=200)),
                ('deadline', models.DateField(auto_now_add=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='warehouse.product')),
            ],
        ),
    ]
