# Generated by Django 4.2.9 on 2024-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
