# Generated by Django 4.2.9 on 2024-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
